# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinerequest', '0002_auto_20170731_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('issue_desc', models.TextField(blank=True, max_length=500, null=True)),
                ('remarks', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_desc',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='remarks',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinerequest.Issue'),
        ),
    ]
