# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinerequest', '0003_auto_20170801_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='value',
            field=models.CharField(max_length=20),
        ),
    ]
