# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinerequest', '0004_auto_20170801_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='date_update',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='transactionlog',
            name='issue_desc',
        ),
    ]
