# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinerequest', '0006_transactionlog_issue_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionlog',
            name='issue',
        ),
        migrations.DeleteModel(
            name='TransactionLog',
        ),
    ]
