# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 09:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onlinerequest', '0008_transactionlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionlog',
            old_name='remarks',
            new_name='updates',
        ),
        migrations.AddField(
            model_name='issue',
            name='ap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
