# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 11:05


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onlinerequest', '0009_auto_20170802_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itadmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='issue',
            name='ap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onlinerequest.Itadmin'),
        ),
    ]
