# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinerequest', '0011_auto_20170803_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='date_assign',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
